// Code generated by goctl. DO NOT EDIT!
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var prefixCarouselCacheKey = "cache:carousel:"

type carouselModel interface {
	Insert(ctx context.Context, data *Carousel) error
	FindOne(ctx context.Context, id string) (*Carousel, error)
	Update(ctx context.Context, data *Carousel) error
	Delete(ctx context.Context, id string) error
}

type defaultCarouselModel struct {
	conn *monc.Model
}

func newDefaultCarouselModel(conn *monc.Model) *defaultCarouselModel {
	return &defaultCarouselModel{conn: conn}
}

func (m *defaultCarouselModel) Insert(ctx context.Context, data *Carousel) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixCarouselCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultCarouselModel) FindOne(ctx context.Context, id string) (*Carousel, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Carousel
	key := prefixCarouselCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarouselModel) Update(ctx context.Context, data *Carousel) error {
	data.UpdateAt = time.Now()
	key := prefixCarouselCacheKey + data.ID.Hex()
	_, err := m.conn.ReplaceOne(ctx, key, bson.M{"_id": data.ID}, data)
	return err
}

func (m *defaultCarouselModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	key := prefixCarouselCacheKey + id
	_, err = m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return err
}
