// Code generated by goctl. DO NOT EDIT!
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var prefixCatCacheKey = "cache:cat:"

type catModel interface {
	Insert(ctx context.Context, data *Cat) error
	FindOne(ctx context.Context, id string) (*Cat, error)
	Update(ctx context.Context, data *Cat) error
	Delete(ctx context.Context, id string) error
}

type defaultCatModel struct {
	conn *monc.Model
}

func newDefaultCatModel(conn *monc.Model) *defaultCatModel {
	return &defaultCatModel{conn: conn}
}

func (m *defaultCatModel) Insert(ctx context.Context, data *Cat) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixCatCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultCatModel) FindOne(ctx context.Context, id string) (*Cat, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Cat
	key := prefixCatCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCatModel) Update(ctx context.Context, data *Cat) error {
	data.UpdateAt = time.Now()
	key := prefixCatCacheKey + data.ID.Hex()
	_, err := m.conn.ReplaceOne(ctx, key, bson.M{"_id": data.ID}, data)
	return err
}

func (m *defaultCatModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	key := prefixCatCacheKey + id
	_, err = m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return err
}
