// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/xh-polaris/meowchat-bff/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/set_password",
				Handler: SetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notice/get_admins",
				Handler: GetAdminsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notice/get_news",
				Handler: GetNewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/get_post_previews",
				Handler: GetPostPreviewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/collection/get_cat_previews",
				Handler: GetCatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/collection/get_cat_detail",
				Handler: GetCatDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/moment/get_moment_previews",
				Handler: GetMomentPreviewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/moment/get_moment_detail",
				Handler: GetMomentDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/sign_in",
				Handler: SignInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/send_verify_code",
				Handler: SendVerifyCodeHandler(serverCtx),
			},
		},
	)
}
