// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: rpc/cat_community.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId         int64  `protobuf:"varint,1,opt,name=catId,proto3" json:"catId,omitempty"`
	Area          string `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	Age           string `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	CampusId      int64  `protobuf:"varint,4,opt,name=campusId,proto3" json:"campusId,omitempty"`
	ColorId       int64  `protobuf:"varint,5,opt,name=colorId,proto3" json:"colorId,omitempty"`
	StatusId      int64  `protobuf:"varint,6,opt,name=statusId,proto3" json:"statusId,omitempty"`
	Popularity    int64  `protobuf:"varint,7,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Detail        string `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`
	Name          string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string `protobuf:"bytes,10,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	SnipEar       int64  `protobuf:"varint,11,opt,name=snipEar,proto3" json:"snipEar,omitempty"`
	Sex           string `protobuf:"bytes,12,opt,name=sex,proto3" json:"sex,omitempty"`
	Sterilization int64  `protobuf:"varint,13,opt,name=sterilization,proto3" json:"sterilization,omitempty"`
}

func (x *Cat) Reset() {
	*x = Cat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_cat_community_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cat) ProtoMessage() {}

func (x *Cat) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_cat_community_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cat.ProtoReflect.Descriptor instead.
func (*Cat) Descriptor() ([]byte, []int) {
	return file_rpc_cat_community_proto_rawDescGZIP(), []int{0}
}

func (x *Cat) GetCatId() int64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *Cat) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Cat) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Cat) GetCampusId() int64 {
	if x != nil {
		return x.CampusId
	}
	return 0
}

func (x *Cat) GetColorId() int64 {
	if x != nil {
		return x.ColorId
	}
	return 0
}

func (x *Cat) GetStatusId() int64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *Cat) GetPopularity() int64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Cat) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Cat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cat) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Cat) GetSnipEar() int64 {
	if x != nil {
		return x.SnipEar
	}
	return 0
}

func (x *Cat) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Cat) GetSterilization() int64 {
	if x != nil {
		return x.Sterilization
	}
	return 0
}

// 根据ID查询猫咪信息
type CatDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CatDetailReq) Reset() {
	*x = CatDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_cat_community_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CatDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatDetailReq) ProtoMessage() {}

func (x *CatDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_cat_community_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatDetailReq.ProtoReflect.Descriptor instead.
func (*CatDetailReq) Descriptor() ([]byte, []int) {
	return file_rpc_cat_community_proto_rawDescGZIP(), []int{1}
}

func (x *CatDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CatDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *Cat `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *CatDetailResp) Reset() {
	*x = CatDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_cat_community_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CatDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatDetailResp) ProtoMessage() {}

func (x *CatDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_cat_community_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatDetailResp.ProtoReflect.Descriptor instead.
func (*CatDetailResp) Descriptor() ([]byte, []int) {
	return file_rpc_cat_community_proto_rawDescGZIP(), []int{2}
}

func (x *CatDetailResp) GetCat() *Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

// 查询猫咪信息
type QueryCatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CampusId int64 `protobuf:"varint,1,opt,name=campusId,proto3" json:"campusId,omitempty"`
	Page     int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size     int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *QueryCatReq) Reset() {
	*x = QueryCatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_cat_community_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCatReq) ProtoMessage() {}

func (x *QueryCatReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_cat_community_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCatReq.ProtoReflect.Descriptor instead.
func (*QueryCatReq) Descriptor() ([]byte, []int) {
	return file_rpc_cat_community_proto_rawDescGZIP(), []int{3}
}

func (x *QueryCatReq) GetCampusId() int64 {
	if x != nil {
		return x.CampusId
	}
	return 0
}

func (x *QueryCatReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryCatReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type QueryCatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatList []*Cat `protobuf:"bytes,1,rep,name=catList,proto3" json:"catList,omitempty"`
}

func (x *QueryCatResp) Reset() {
	*x = QueryCatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_cat_community_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCatResp) ProtoMessage() {}

func (x *QueryCatResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_cat_community_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCatResp.ProtoReflect.Descriptor instead.
func (*QueryCatResp) Descriptor() ([]byte, []int) {
	return file_rpc_cat_community_proto_rawDescGZIP(), []int{4}
}

func (x *QueryCatResp) GetCatList() []*Cat {
	if x != nil {
		return x.CatList
	}
	return nil
}

// 上传猫咪信息
type UploadCatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *Cat `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *UploadCatReq) Reset() {
	*x = UploadCatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_cat_community_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCatReq) ProtoMessage() {}

func (x *UploadCatReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_cat_community_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCatReq.ProtoReflect.Descriptor instead.
func (*UploadCatReq) Descriptor() ([]byte, []int) {
	return file_rpc_cat_community_proto_rawDescGZIP(), []int{5}
}

func (x *UploadCatReq) GetCat() *Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type UploadCatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadCatResp) Reset() {
	*x = UploadCatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_cat_community_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCatResp) ProtoMessage() {}

func (x *UploadCatResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_cat_community_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCatResp.ProtoReflect.Descriptor instead.
func (*UploadCatResp) Descriptor() ([]byte, []int) {
	return file_rpc_cat_community_proto_rawDescGZIP(), []int{6}
}

var File_rpc_cat_community_proto protoreflect.FileDescriptor

var file_rpc_cat_community_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x61, 0x74, 0x22, 0xcf,
	0x02, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x6e, 0x69, 0x70, 0x45, 0x61, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x73, 0x6e, 0x69, 0x70, 0x45, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74,
	0x65, 0x72, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x73, 0x74, 0x65, 0x72, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x1e, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2b, 0x0a, 0x0d, 0x43, 0x61, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1a, 0x0a, 0x03, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x52, 0x03, 0x63, 0x61, 0x74, 0x22, 0x51, 0x0a,
	0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x32, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x22, 0x0a, 0x07, 0x63, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x52, 0x07, 0x63, 0x61, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x03, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x52, 0x03, 0x63, 0x61, 0x74,
	0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x32, 0xa7, 0x01, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x12, 0x32, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x11, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x72, 0x79, 0x43,
	0x61, 0x74, 0x12, 0x10, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x43, 0x61, 0x74, 0x12, 0x11, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_cat_community_proto_rawDescOnce sync.Once
	file_rpc_cat_community_proto_rawDescData = file_rpc_cat_community_proto_rawDesc
)

func file_rpc_cat_community_proto_rawDescGZIP() []byte {
	file_rpc_cat_community_proto_rawDescOnce.Do(func() {
		file_rpc_cat_community_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_cat_community_proto_rawDescData)
	})
	return file_rpc_cat_community_proto_rawDescData
}

var file_rpc_cat_community_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_cat_community_proto_goTypes = []interface{}{
	(*Cat)(nil),           // 0: cat.Cat
	(*CatDetailReq)(nil),  // 1: cat.CatDetailReq
	(*CatDetailResp)(nil), // 2: cat.CatDetailResp
	(*QueryCatReq)(nil),   // 3: cat.QueryCatReq
	(*QueryCatResp)(nil),  // 4: cat.QueryCatResp
	(*UploadCatReq)(nil),  // 5: cat.UploadCatReq
	(*UploadCatResp)(nil), // 6: cat.UploadCatResp
}
var file_rpc_cat_community_proto_depIdxs = []int32{
	0, // 0: cat.CatDetailResp.cat:type_name -> cat.Cat
	0, // 1: cat.QueryCatResp.catList:type_name -> cat.Cat
	0, // 2: cat.UploadCatReq.cat:type_name -> cat.Cat
	1, // 3: cat.CatCommunity.getDetail:input_type -> cat.CatDetailReq
	3, // 4: cat.CatCommunity.queryCat:input_type -> cat.QueryCatReq
	5, // 5: cat.CatCommunity.uploadCat:input_type -> cat.UploadCatReq
	2, // 6: cat.CatCommunity.getDetail:output_type -> cat.CatDetailResp
	4, // 7: cat.CatCommunity.queryCat:output_type -> cat.QueryCatResp
	6, // 8: cat.CatCommunity.uploadCat:output_type -> cat.UploadCatResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_cat_community_proto_init() }
func file_rpc_cat_community_proto_init() {
	if File_rpc_cat_community_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_cat_community_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_cat_community_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CatDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_cat_community_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CatDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_cat_community_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_cat_community_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_cat_community_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_cat_community_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_cat_community_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_cat_community_proto_goTypes,
		DependencyIndexes: file_rpc_cat_community_proto_depIdxs,
		MessageInfos:      file_rpc_cat_community_proto_msgTypes,
	}.Build()
	File_rpc_cat_community_proto = out.File
	file_rpc_cat_community_proto_rawDesc = nil
	file_rpc_cat_community_proto_goTypes = nil
	file_rpc_cat_community_proto_depIdxs = nil
}
